//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IPHelp.Eztop {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EDTSManager", Namespace="http://EDTS.DirectTopUpServices.ServiceContracts/2006/10")]
    public partial class EDTSManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TopUpPhoneAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTargetTopUpAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidatePhoneAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductListOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsCountrySupportedByEzeOperatorOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopUpTransactionStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public EDTSManager() {
            this.Url = global::IPHelp.Properties.Settings.Default.IPHelp_Eztop_EDTSManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TopUpPhoneAccountCompletedEventHandler TopUpPhoneAccountCompleted;
        
        /// <remarks/>
        public event GetTargetTopUpAmountCompletedEventHandler GetTargetTopUpAmountCompleted;
        
        /// <remarks/>
        public event ValidatePhoneAccountCompletedEventHandler ValidatePhoneAccountCompleted;
        
        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;
        
        /// <remarks/>
        public event GetBalanceCompletedEventHandler GetBalanceCompleted;
        
        /// <remarks/>
        public event GetProductListCompletedEventHandler GetProductListCompleted;
        
        /// <remarks/>
        public event IsCountrySupportedByEzeOperatorCompletedEventHandler IsCountrySupportedByEzeOperatorCompleted;
        
        /// <remarks/>
        public event GetTopUpTransactionStatusCompletedEventHandler GetTopUpTransactionStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EDTS.DirectTopUpServices.ServiceContracts/2006/10/TopUpPhoneAccount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
        public TopUpPhoneAccountResponse TopUpPhoneAccount([System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")] TopUpPhoneAccountRequest TopUpPhoneAccountRequest) {
            object[] results = this.Invoke("TopUpPhoneAccount", new object[] {
                        TopUpPhoneAccountRequest});
            return ((TopUpPhoneAccountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void TopUpPhoneAccountAsync(TopUpPhoneAccountRequest TopUpPhoneAccountRequest) {
            this.TopUpPhoneAccountAsync(TopUpPhoneAccountRequest, null);
        }
        
        /// <remarks/>
        public void TopUpPhoneAccountAsync(TopUpPhoneAccountRequest TopUpPhoneAccountRequest, object userState) {
            if ((this.TopUpPhoneAccountOperationCompleted == null)) {
                this.TopUpPhoneAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTopUpPhoneAccountOperationCompleted);
            }
            this.InvokeAsync("TopUpPhoneAccount", new object[] {
                        TopUpPhoneAccountRequest}, this.TopUpPhoneAccountOperationCompleted, userState);
        }
        
        private void OnTopUpPhoneAccountOperationCompleted(object arg) {
            if ((this.TopUpPhoneAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TopUpPhoneAccountCompleted(this, new TopUpPhoneAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EDTS.DirectTopUpServices.ServiceContracts/2006/10/GetTargetTopUpAmount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
        public GetTargetTopUpAmountResponse GetTargetTopUpAmount([System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")] GetTargetTopUpAmountRequest GetTargetTopUpAmountRequest) {
            object[] results = this.Invoke("GetTargetTopUpAmount", new object[] {
                        GetTargetTopUpAmountRequest});
            return ((GetTargetTopUpAmountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTargetTopUpAmountAsync(GetTargetTopUpAmountRequest GetTargetTopUpAmountRequest) {
            this.GetTargetTopUpAmountAsync(GetTargetTopUpAmountRequest, null);
        }
        
        /// <remarks/>
        public void GetTargetTopUpAmountAsync(GetTargetTopUpAmountRequest GetTargetTopUpAmountRequest, object userState) {
            if ((this.GetTargetTopUpAmountOperationCompleted == null)) {
                this.GetTargetTopUpAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTargetTopUpAmountOperationCompleted);
            }
            this.InvokeAsync("GetTargetTopUpAmount", new object[] {
                        GetTargetTopUpAmountRequest}, this.GetTargetTopUpAmountOperationCompleted, userState);
        }
        
        private void OnGetTargetTopUpAmountOperationCompleted(object arg) {
            if ((this.GetTargetTopUpAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTargetTopUpAmountCompleted(this, new GetTargetTopUpAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EDTS.DirectTopUpServices.ServiceContracts/2006/10/ValidatePhoneAccount", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
        public ValidatePhoneAccountResponse ValidatePhoneAccount([System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")] ValidatePhoneAccountRequest ValidatePhoneAccountRequest) {
            object[] results = this.Invoke("ValidatePhoneAccount", new object[] {
                        ValidatePhoneAccountRequest});
            return ((ValidatePhoneAccountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ValidatePhoneAccountAsync(ValidatePhoneAccountRequest ValidatePhoneAccountRequest) {
            this.ValidatePhoneAccountAsync(ValidatePhoneAccountRequest, null);
        }
        
        /// <remarks/>
        public void ValidatePhoneAccountAsync(ValidatePhoneAccountRequest ValidatePhoneAccountRequest, object userState) {
            if ((this.ValidatePhoneAccountOperationCompleted == null)) {
                this.ValidatePhoneAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidatePhoneAccountOperationCompleted);
            }
            this.InvokeAsync("ValidatePhoneAccount", new object[] {
                        ValidatePhoneAccountRequest}, this.ValidatePhoneAccountOperationCompleted, userState);
        }
        
        private void OnValidatePhoneAccountOperationCompleted(object arg) {
            if ((this.ValidatePhoneAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidatePhoneAccountCompleted(this, new ValidatePhoneAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EDTS.DirectTopUpServices.ServiceContracts/2006/10/SendSMS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
        public SendSMSResponse SendSMS([System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")] SendSMSRequest SendSMSRequest) {
            object[] results = this.Invoke("SendSMS", new object[] {
                        SendSMSRequest});
            return ((SendSMSResponse)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSAsync(SendSMSRequest SendSMSRequest) {
            this.SendSMSAsync(SendSMSRequest, null);
        }
        
        /// <remarks/>
        public void SendSMSAsync(SendSMSRequest SendSMSRequest, object userState) {
            if ((this.SendSMSOperationCompleted == null)) {
                this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[] {
                        SendSMSRequest}, this.SendSMSOperationCompleted, userState);
        }
        
        private void OnSendSMSOperationCompleted(object arg) {
            if ((this.SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EDTS.DirectTopUpServices.ServiceContracts/2010/06/GetBalance", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
        public GetBalanceResponse GetBalance([System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")] GetBalanceRequest GetBalanceRequest) {
            object[] results = this.Invoke("GetBalance", new object[] {
                        GetBalanceRequest});
            return ((GetBalanceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetBalanceAsync(GetBalanceRequest GetBalanceRequest) {
            this.GetBalanceAsync(GetBalanceRequest, null);
        }
        
        /// <remarks/>
        public void GetBalanceAsync(GetBalanceRequest GetBalanceRequest, object userState) {
            if ((this.GetBalanceOperationCompleted == null)) {
                this.GetBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBalanceOperationCompleted);
            }
            this.InvokeAsync("GetBalance", new object[] {
                        GetBalanceRequest}, this.GetBalanceOperationCompleted, userState);
        }
        
        private void OnGetBalanceOperationCompleted(object arg) {
            if ((this.GetBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBalanceCompleted(this, new GetBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EDTS.DirectTopUpServices.ServiceContracts/2010/07/GetProductList", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
        public GetProductListResponse GetProductList([System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")] GetProductListRequest GetProductListRequest) {
            object[] results = this.Invoke("GetProductList", new object[] {
                        GetProductListRequest});
            return ((GetProductListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductListAsync(GetProductListRequest GetProductListRequest) {
            this.GetProductListAsync(GetProductListRequest, null);
        }
        
        /// <remarks/>
        public void GetProductListAsync(GetProductListRequest GetProductListRequest, object userState) {
            if ((this.GetProductListOperationCompleted == null)) {
                this.GetProductListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductListOperationCompleted);
            }
            this.InvokeAsync("GetProductList", new object[] {
                        GetProductListRequest}, this.GetProductListOperationCompleted, userState);
        }
        
        private void OnGetProductListOperationCompleted(object arg) {
            if ((this.GetProductListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductListCompleted(this, new GetProductListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EDTS.DirectTopUpServices.ServiceContracts/2011/05/IsCountrySupportedByEzeO" +
            "perator", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2011/05")]
        public IsCountrySupportedByEzeOperatorResponse IsCountrySupportedByEzeOperator([System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2011/05")] IsCountrySupportedByEzeOperatorRequest request) {
            object[] results = this.Invoke("IsCountrySupportedByEzeOperator", new object[] {
                        request});
            return ((IsCountrySupportedByEzeOperatorResponse)(results[0]));
        }
        
        /// <remarks/>
        public void IsCountrySupportedByEzeOperatorAsync(IsCountrySupportedByEzeOperatorRequest request) {
            this.IsCountrySupportedByEzeOperatorAsync(request, null);
        }
        
        /// <remarks/>
        public void IsCountrySupportedByEzeOperatorAsync(IsCountrySupportedByEzeOperatorRequest request, object userState) {
            if ((this.IsCountrySupportedByEzeOperatorOperationCompleted == null)) {
                this.IsCountrySupportedByEzeOperatorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsCountrySupportedByEzeOperatorOperationCompleted);
            }
            this.InvokeAsync("IsCountrySupportedByEzeOperator", new object[] {
                        request}, this.IsCountrySupportedByEzeOperatorOperationCompleted, userState);
        }
        
        private void OnIsCountrySupportedByEzeOperatorOperationCompleted(object arg) {
            if ((this.IsCountrySupportedByEzeOperatorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsCountrySupportedByEzeOperatorCompleted(this, new IsCountrySupportedByEzeOperatorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://EDTS.DirectTopUpServices.ServiceContracts/2012/04/GetTopUpTransactionStatu" +
            "s", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2012/03")]
        public GetTopUpTransactionStatusResponse GetTopUpTransactionStatus([System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2012/03")] GetTopUpTransactionStatusRequest request) {
            object[] results = this.Invoke("GetTopUpTransactionStatus", new object[] {
                        request});
            return ((GetTopUpTransactionStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopUpTransactionStatusAsync(GetTopUpTransactionStatusRequest request) {
            this.GetTopUpTransactionStatusAsync(request, null);
        }
        
        /// <remarks/>
        public void GetTopUpTransactionStatusAsync(GetTopUpTransactionStatusRequest request, object userState) {
            if ((this.GetTopUpTransactionStatusOperationCompleted == null)) {
                this.GetTopUpTransactionStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopUpTransactionStatusOperationCompleted);
            }
            this.InvokeAsync("GetTopUpTransactionStatus", new object[] {
                        request}, this.GetTopUpTransactionStatusOperationCompleted, userState);
        }
        
        private void OnGetTopUpTransactionStatusOperationCompleted(object arg) {
            if ((this.GetTopUpTransactionStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopUpTransactionStatusCompleted(this, new GetTopUpTransactionStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class TopUpPhoneAccountRequest {
        
        private AuthenticationToken authenticationTokenField;
        
        private int messageIDField;
        
        private string countryCodeField;
        
        private string operatorCodeField;
        
        private string phoneNumberField;
        
        private double amountField;
        
        private string commentField;
        
        private SendSMSRequest sMSRequestField;
        
        /// <remarks/>
        public AuthenticationToken AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
            }
        }
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public SendSMSRequest SMSRequest {
            get {
                return this.sMSRequestField;
            }
            set {
                this.sMSRequestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class AuthenticationToken {
        
        private string authenticationIDField;
        
        private string authenticationPasswordField;
        
        /// <remarks/>
        public string AuthenticationID {
            get {
                return this.authenticationIDField;
            }
            set {
                this.authenticationIDField = value;
            }
        }
        
        /// <remarks/>
        public string AuthenticationPassword {
            get {
                return this.authenticationPasswordField;
            }
            set {
                this.authenticationPasswordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2012/03")]
    public partial class GetTopUpTransactionStatusResponse {
        
        private int statusField;
        
        private string statusDescriptionField;
        
        private TopUpPhoneAccountResponse topUpPhoneAccountResultField;
        
        private System.Nullable<System.DateTime> topUpTimestampField;
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
        public TopUpPhoneAccountResponse TopUpPhoneAccountResult {
            get {
                return this.topUpPhoneAccountResultField;
            }
            set {
                this.topUpPhoneAccountResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> TopUpTimestamp {
            get {
                return this.topUpTimestampField;
            }
            set {
                this.topUpTimestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class TopUpPhoneAccountResponse {
        
        private int messageIDField;
        
        private TopUpPhoneAccountStatus topUpPhoneAccountStatusField;
        
        private SendSMSStatus sMSStatusField;
        
        private TopUpPhoneAccountAmountSent topUpPhoneAccountAmountSentField;
        
        private string operatorCodeField;
        
        private string operatorNameField;
        
        private string mobileNetworkCodeField;
        
        private string countryCodeField;
        
        private string countryNameField;
        
        private string mobileCountryCodeField;
        
        private string customerCareNumberField;
        
        private string logoURLField;
        
        private string transactionFeeField;
        
        private Denomination denominationsField;
        
        private MinMaxValueRange minMaxValueRangeField;
        
        private string textDisclaimerField;
        
        private string textDisclaimer2Field;
        
        private string textAdditionalField;
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public TopUpPhoneAccountStatus TopUpPhoneAccountStatus {
            get {
                return this.topUpPhoneAccountStatusField;
            }
            set {
                this.topUpPhoneAccountStatusField = value;
            }
        }
        
        /// <remarks/>
        public SendSMSStatus SMSStatus {
            get {
                return this.sMSStatusField;
            }
            set {
                this.sMSStatusField = value;
            }
        }
        
        /// <remarks/>
        public TopUpPhoneAccountAmountSent TopUpPhoneAccountAmountSent {
            get {
                return this.topUpPhoneAccountAmountSentField;
            }
            set {
                this.topUpPhoneAccountAmountSentField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNetworkCode {
            get {
                return this.mobileNetworkCodeField;
            }
            set {
                this.mobileNetworkCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public string MobileCountryCode {
            get {
                return this.mobileCountryCodeField;
            }
            set {
                this.mobileCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCareNumber {
            get {
                return this.customerCareNumberField;
            }
            set {
                this.customerCareNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LogoURL {
            get {
                return this.logoURLField;
            }
            set {
                this.logoURLField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionFee {
            get {
                return this.transactionFeeField;
            }
            set {
                this.transactionFeeField = value;
            }
        }
        
        /// <remarks/>
        public Denomination Denominations {
            get {
                return this.denominationsField;
            }
            set {
                this.denominationsField = value;
            }
        }
        
        /// <remarks/>
        public MinMaxValueRange MinMaxValueRange {
            get {
                return this.minMaxValueRangeField;
            }
            set {
                this.minMaxValueRangeField = value;
            }
        }
        
        /// <remarks/>
        public string TextDisclaimer {
            get {
                return this.textDisclaimerField;
            }
            set {
                this.textDisclaimerField = value;
            }
        }
        
        /// <remarks/>
        public string TextDisclaimer2 {
            get {
                return this.textDisclaimer2Field;
            }
            set {
                this.textDisclaimer2Field = value;
            }
        }
        
        /// <remarks/>
        public string TextAdditional {
            get {
                return this.textAdditionalField;
            }
            set {
                this.textAdditionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class TopUpPhoneAccountStatus {
        
        private int statusIDField;
        
        private string statusDescriptionField;
        
        private int confirmationIDField;
        
        /// <remarks/>
        public int StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int ConfirmationID {
            get {
                return this.confirmationIDField;
            }
            set {
                this.confirmationIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class SendSMSStatus {
        
        private int statusIDField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        public int StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class TopUpPhoneAccountAmountSent {
        
        private double amountField;
        
        private double amountExcludingTaxField;
        
        private string taxNameField;
        
        private double taxAmountField;
        
        private string currencyCodeField;
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public double AmountExcludingTax {
            get {
                return this.amountExcludingTaxField;
            }
            set {
                this.amountExcludingTaxField = value;
            }
        }
        
        /// <remarks/>
        public string TaxName {
            get {
                return this.taxNameField;
            }
            set {
                this.taxNameField = value;
            }
        }
        
        /// <remarks/>
        public double TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class Denomination {
        
        private int numberOfDenominationsField;
        
        private double[] denominationsField;
        
        /// <remarks/>
        public int NumberOfDenominations {
            get {
                return this.numberOfDenominationsField;
            }
            set {
                this.numberOfDenominationsField = value;
            }
        }
        
        /// <remarks/>
        public double[] Denominations {
            get {
                return this.denominationsField;
            }
            set {
                this.denominationsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class MinMaxValueRange {
        
        private double minValueField;
        
        private double maxValueField;
        
        /// <remarks/>
        public double MinValue {
            get {
                return this.minValueField;
            }
            set {
                this.minValueField = value;
            }
        }
        
        /// <remarks/>
        public double MaxValue {
            get {
                return this.maxValueField;
            }
            set {
                this.maxValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2012/03")]
    public partial class GetTopUpTransactionStatusRequest {
        
        private AuthenticationToken authenticationTokenField;
        
        private int messageIDField;
        
        private string phoneNumberField;
        
        /// <remarks/>
        public AuthenticationToken AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
            }
        }
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2011/05")]
    public partial class IsCountrySupportedByEzeOperatorResponse {
        
        private int messageIdField;
        
        private bool countryIsSupportedField;
        
        private int statusIdField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        public int MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public bool CountryIsSupported {
            get {
                return this.countryIsSupportedField;
            }
            set {
                this.countryIsSupportedField = value;
            }
        }
        
        /// <remarks/>
        public int StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2011/05")]
    public partial class IsCountrySupportedByEzeOperatorRequest {
        
        private int messageIdField;
        
        private AuthenticationToken authenticationTokenField;
        
        private string countryIsoField;
        
        /// <remarks/>
        public int MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public AuthenticationToken AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
            }
        }
        
        /// <remarks/>
        public string CountryIso {
            get {
                return this.countryIsoField;
            }
            set {
                this.countryIsoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class Product {
        
        private int countryIDField;
        
        private string countryISOField;
        
        private string countryCodeField;
        
        private string countryNameField;
        
        private int operatorIDField;
        
        private string operatorCodeField;
        
        private string operatorNameField;
        
        private string logoUrlField;
        
        private string commercialCodeField;
        
        private string customerCareNumberField;
        
        private string phoneNumberMaskField;
        
        private Denomination denominationsField;
        
        private MinMaxValueRange minMaxValueRangeField;
        
        /// <remarks/>
        public int CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string CountryISO {
            get {
                return this.countryISOField;
            }
            set {
                this.countryISOField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public int OperatorID {
            get {
                return this.operatorIDField;
            }
            set {
                this.operatorIDField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
        
        /// <remarks/>
        public string LogoUrl {
            get {
                return this.logoUrlField;
            }
            set {
                this.logoUrlField = value;
            }
        }
        
        /// <remarks/>
        public string CommercialCode {
            get {
                return this.commercialCodeField;
            }
            set {
                this.commercialCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCareNumber {
            get {
                return this.customerCareNumberField;
            }
            set {
                this.customerCareNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumberMask {
            get {
                return this.phoneNumberMaskField;
            }
            set {
                this.phoneNumberMaskField = value;
            }
        }
        
        /// <remarks/>
        public Denomination Denominations {
            get {
                return this.denominationsField;
            }
            set {
                this.denominationsField = value;
            }
        }
        
        /// <remarks/>
        public MinMaxValueRange MinMaxValueRange {
            get {
                return this.minMaxValueRangeField;
            }
            set {
                this.minMaxValueRangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class GetProductListResponse {
        
        private int messageIDField;
        
        private Product[] productsField;
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public Product[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class GetProductListRequest {
        
        private int messageIDField;
        
        private AuthenticationToken authenticationTokenField;
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public AuthenticationToken AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class GetBalanceResponse {
        
        private int messageIDField;
        
        private decimal balanceField;
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class GetBalanceRequest {
        
        private int messageIDField;
        
        private AuthenticationToken authenticationTokenField;
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public AuthenticationToken AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class SendSMSResponse {
        
        private int messageIDField;
        
        private SendSMSStatus sMSStatusField;
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public SendSMSStatus SMSStatus {
            get {
                return this.sMSStatusField;
            }
            set {
                this.sMSStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class ValidatePhoneAccountStatus {
        
        private int statusIDField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        public int StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class ValidatePhoneAccountResponse {
        
        private int messageIDField;
        
        private ValidatePhoneAccountStatus validatePhoneAccountStatusField;
        
        private Denomination denominationsField;
        
        private MinMaxValueRange minMaxValueRangeField;
        
        private string countryCodeField;
        
        private string countryNameField;
        
        private string mobileCountryCodeField;
        
        private string operatorCodeField;
        
        private string operatorNameField;
        
        private string mobileNetworkCodeField;
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public ValidatePhoneAccountStatus ValidatePhoneAccountStatus {
            get {
                return this.validatePhoneAccountStatusField;
            }
            set {
                this.validatePhoneAccountStatusField = value;
            }
        }
        
        /// <remarks/>
        public Denomination Denominations {
            get {
                return this.denominationsField;
            }
            set {
                this.denominationsField = value;
            }
        }
        
        /// <remarks/>
        public MinMaxValueRange MinMaxValueRange {
            get {
                return this.minMaxValueRangeField;
            }
            set {
                this.minMaxValueRangeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        public string MobileCountryCode {
            get {
                return this.mobileCountryCodeField;
            }
            set {
                this.mobileCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorName {
            get {
                return this.operatorNameField;
            }
            set {
                this.operatorNameField = value;
            }
        }
        
        /// <remarks/>
        public string MobileNetworkCode {
            get {
                return this.mobileNetworkCodeField;
            }
            set {
                this.mobileNetworkCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class ValidatePhoneAccountRequest {
        
        private AuthenticationToken authenticationTokenField;
        
        private int messageIDField;
        
        private string countryCodeField;
        
        private string operatorCodeField;
        
        private string phoneNumberField;
        
        private double amountField;
        
        /// <remarks/>
        public AuthenticationToken AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
            }
        }
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class GetTargetTopUpAmountStatus {
        
        private int statusIDField;
        
        private string statusDescriptionField;
        
        /// <remarks/>
        public int StatusID {
            get {
                return this.statusIDField;
            }
            set {
                this.statusIDField = value;
            }
        }
        
        /// <remarks/>
        public string StatusDescription {
            get {
                return this.statusDescriptionField;
            }
            set {
                this.statusDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class GetTargetTopUpAmountResponse {
        
        private int messageIDField;
        
        private string countryCodeField;
        
        private double amountField;
        
        private double amountExcludingTaxField;
        
        private string taxNameField;
        
        private double taxAmountField;
        
        private string currencyCodeField;
        
        private GetTargetTopUpAmountStatus getTargetTopUpAmountStatusField;
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public double AmountExcludingTax {
            get {
                return this.amountExcludingTaxField;
            }
            set {
                this.amountExcludingTaxField = value;
            }
        }
        
        /// <remarks/>
        public string TaxName {
            get {
                return this.taxNameField;
            }
            set {
                this.taxNameField = value;
            }
        }
        
        /// <remarks/>
        public double TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        public GetTargetTopUpAmountStatus GetTargetTopUpAmountStatus {
            get {
                return this.getTargetTopUpAmountStatusField;
            }
            set {
                this.getTargetTopUpAmountStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class GetTargetTopUpAmountRequest {
        
        private AuthenticationToken authenticationTokenField;
        
        private int messageIDField;
        
        private string countryCodeField;
        
        private string operatorCodeField;
        
        private double amountField;
        
        /// <remarks/>
        public AuthenticationToken AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
            }
        }
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://EDTS.DirectTopUpServices.DataTypes/2006/10")]
    public partial class SendSMSRequest {
        
        private AuthenticationToken authenticationTokenField;
        
        private int messageIDField;
        
        private string countryCodeField;
        
        private string operatorCodeField;
        
        private string messagePhoneNumberField;
        
        private string messageTextField;
        
        private string messageFromField;
        
        /// <remarks/>
        public AuthenticationToken AuthenticationToken {
            get {
                return this.authenticationTokenField;
            }
            set {
                this.authenticationTokenField = value;
            }
        }
        
        /// <remarks/>
        public int MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string OperatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string MessagePhoneNumber {
            get {
                return this.messagePhoneNumberField;
            }
            set {
                this.messagePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MessageText {
            get {
                return this.messageTextField;
            }
            set {
                this.messageTextField = value;
            }
        }
        
        /// <remarks/>
        public string MessageFrom {
            get {
                return this.messageFromField;
            }
            set {
                this.messageFromField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void TopUpPhoneAccountCompletedEventHandler(object sender, TopUpPhoneAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TopUpPhoneAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TopUpPhoneAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TopUpPhoneAccountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TopUpPhoneAccountResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetTargetTopUpAmountCompletedEventHandler(object sender, GetTargetTopUpAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTargetTopUpAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTargetTopUpAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetTargetTopUpAmountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetTargetTopUpAmountResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ValidatePhoneAccountCompletedEventHandler(object sender, ValidatePhoneAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidatePhoneAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidatePhoneAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidatePhoneAccountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidatePhoneAccountResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SendSMSResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SendSMSResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetBalanceCompletedEventHandler(object sender, GetBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetBalanceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetBalanceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetProductListCompletedEventHandler(object sender, GetProductListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetProductListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetProductListResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IsCountrySupportedByEzeOperatorCompletedEventHandler(object sender, IsCountrySupportedByEzeOperatorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsCountrySupportedByEzeOperatorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsCountrySupportedByEzeOperatorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IsCountrySupportedByEzeOperatorResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IsCountrySupportedByEzeOperatorResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void GetTopUpTransactionStatusCompletedEventHandler(object sender, GetTopUpTransactionStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopUpTransactionStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopUpTransactionStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetTopUpTransactionStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetTopUpTransactionStatusResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591